Mobile menu session
asharanjith/Portfolio-Asha pull request #11
Opened 2022-10-10 14:33 UTC by asharanjith

In this session,

- Create the mobile menu view
- Used JS DOM to navigate through the portfolio

2022-10-10 14:39 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @asharanjith, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that does not have commits from your partner. This is a pair programming project and requires commits from both partners

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-11 08:15 UTC, Davidosky007 reviewed
Hi @asharanjith @solomonetchu @eyoab01 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't show linter check actions kindly fix this  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-11 08:24 UTC, ichala requested changes
Hi @asharanjith  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

1. 🛑 You have submitted a project, that doesn't have javascript linters installed, kindly add [Javascripts Linters](https://github.com/microverseinc/linters-config/tree/master/javascript) with your HTML and CSS linters 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-11 08:32 UTC, asharanjith commented
@ichala Hi I have already installed the ESLint in this project, added the .eslintrc.json file, and run the same. Kindly guide me if anything else need to be done.

2022-10-11 09:13 UTC, topeogunleye requested changes
Hi @asharanjith, @tesfaye

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
_Check the comments under the review._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-11 09:13 UTC, topeogunleye commented on index.html
>          <nav class="nav-bar">
> * Kindly ensure that you Overlay covers the whole page as seen in the Figma Design and add a little bit of blur to your overlay in order to match the Figma design and also make a good contrast 🎨 👨🏻‍🎨
> * Great job so far 🙌 but I think it would be better if you could use a `position: sticky;` on your Navbar. Sticky elements are positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). . The navigation is always displayed after the user stops scrolling. Please change this. This will make your website similar to the original design. 💯 🥇
> * Nice implementing the design; however, it would be better if you add a little bit of blur to your overlay in order to match the Figma design and also make a good contrast 🎨 👨🏻‍🎨
> 
> ### Adding these features will make your design look great and look exactly like the Figma design, I'll make this as an optional requiement since the previous reviewer is skipping this but I highly recommend you do this in the meantime,
>


| Your Design  | Figma Design |
| ------------- | ------------- |
| <img width="301" alt="image" src="https://user-images.githubusercontent.com/52934128/195045166-a53e35b2-729f-4d91-93aa-6974f067d5f0.png"> |  ![image](https://user-images.githubusercontent.com/61790587/167505757-7e8c3eba-c166-4f42-842b-829d676cabd5.png)  |
| Content Cell  | Content Cell  |


> * [OPTIONAL] What about preventing the body from scrolling when the navbar is open? You can use a CSS property `over-flow: hidden;` on the body to do that, which will make your mobile menu correspond to the original design.💯 🥇

2022-10-11 09:13 UTC, topeogunleye commented on index.html
>            <i class="fas fa-bars" id="hamburger"></i>
- [ ] As required, I kindly suggest that you ensure that the hamburger menu isn't visible on desktop.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/52934128/195047218-a4afc9ef-2271-42be-98c3-14e580978ae8.png">

2022-10-11 10:49 UTC, dasileker approved these changes
### **Hi @asharanjith,** 

### **Highlight**

- Nicely done on making all the required changes to the project.

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-11 11:41 UTC, merged